export const TODO_ADD_TODO = "ADD_TODO"
export const TODO_TOGGLE_TODO = "TOGGLE_TODO"
export const FILTER_FILTER_TODO = "FILTER_TODO"
export const FILTER_SHOW_COMPLETE = "SHOW_COMPLETE"
export const FILTER_SHOW_ACTIVE = "SHOW_ACTIVE"
export const FILTER_SHOW_ALL = "SHOW_ALL"
export const API_FETCH_REQUEST = "MY_FETCH_REQUEST"
export const API_FETCH_SUCCESS = "MY_FETCH_SUCCESS"
export const API_FETCH_ERROR = "MY_FETCH_ERROR"




  
  



 
